### ISSUE TITLE
[BUG] explorer crashes when adding the create identifier widget

### ISSUE THREAD

**Issue by mirceanis** [veramolabs/agent-explorer#80]
The https://explore.veramo.dev page crashes when adding a Create Identifier widget to the Dashboard.

Steps to reproduce:
* Go to https://explore.veramo.dev
* add an agent using the schema URL https://demo-veramo-agent.herokuapp.com/open-api.json and the API key: `demo`
* go to dashboard and add `Create Identifier` widget
* the dashboard crashes and does not recover until site settings are cleared

```
react-dom.production.min.js:216 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Hl (react-dom.production.min.js:280:177)
    at d (react-dom.production.min.js:143:356)
    at m (react-dom.production.min.js:146:132)
    at react-dom.production.min.js:150:224
    at Ai (react-dom.production.min.js:176:186)
    at zi (react-dom.production.min.js:179:470)
    at Ks (react-dom.production.min.js:274:466)
    at kl (react-dom.production.min.js:250:347)
    at _l (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
ss @ react-dom.production.min.js:216
react-dom.production.min.js:280 Uncaught Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Hl (react-dom.production.min.js:280:177)
    at d (react-dom.production.min.js:143:356)
    at m (react-dom.production.min.js:146:132)
    at react-dom.production.min.js:150:224
    at Ai (react-dom.production.min.js:176:186)
    at zi (react-dom.production.min.js:179:470)
    at Ks (react-dom.production.min.js:274:466)
    at kl (react-dom.production.min.js:250:347)
    at _l (react-dom.production.min.js:250:278)
    at Cl (react-dom.production.min.js:250:138)
```

**Comment by nickreynolds** [comment]
I believe I fixed this in https://github.com/veramolabs/agent-explorer/pull/71 - but now realizing I'm not sure how to push latest version to https://explore.veramo.dev - I assumed it would happen automatically via github actions but possibly not

**Comment by nickreynolds** [comment]
fix has been deployed
